# FAQ

<패스트캠퍼스 결제내역 EDA PJT>
1. 쿠폰 발행 기준이 어떻게 되는지
==> 특별한 기준은 없습니다. 크게 아래와 같이 구분 가능합니다.

  (1) 전사적으로 매달 프로모션 부서에서 발급하는 쿠폰

  (2) 회원가입 시 증정하는 쿠폰

  (3) 강의별로 진행하는 독립적인 쿠폰 등


2. 이윤기준 (정확한 원가 정보가 아니더라도 얼마 정도가 되야 이윤이 발생하는지)
    a. 강의 제작비용(원가)
    b. BEP기준 (수강생 수, 가격)
    c. 강의 제작시 기대수익
==> BEP를 중요한 기준으로 삼지 않습니다. 일반적으로 코스 당 한달에 3~5천만원 매출 달성을 목표로 삼습니다.


3. 회계처리방식
( 100% 할인해주는 쿠폰의 경우 비용으로 들어가는지 or 손실로 처리하는지 )
==> 마케팅 비용으로 처리해서 보시면 되겠습니다.


4. 중복할인
(중복할인이 어떻게 적용되는지, 쿠폰 중복할인 / 쿠폰과PG사 간 중복할인, 중복할인이 될 경우 할인된 금액은 각각 누가 부담하는지)
==> 쿠폰의 중복사용 불가능합니다.


5. Type
- refund일 경우 payment 데이터의 type을 refund로 변경하나요
아니면 두 개의 데이터(payment, refund)를 가지고 있나요?
==> type의 변경은 없습니다. 두개의 데이터를 가지고 있다고 보시면 되겠습니다.


6. State
- CANCELLED, COMPLETED, DELETED, PENDING은 각각 어떤 의미인가요?
CANCELLED : 환불과는 다르게 결제 취소가 되는 것인지
PENDING : pg사로부터 정산 전인 것인지
DELETED : 시스템 오류로 삭제된 건가요? 없는데이터로 판단하면 되는지
==> completed만 봐주시기 바랍니다.


7. method
- POINT, PROMOTION, TRANS, TRANSFER, VBANK 각각 어떤 의미인가요?
- method == Image인 경우 / 내부 검수용, 맥북 패스 수강 쿠폰사용으로 0원 결제가 되어 있는데, 그로스팀에서 해당 데이터도 매출로 측정하나요?
- TRANSFER 의 경우 pg사가 공란인데 어떻게 결제된건가요?
==> 공란도 어떤 값을 가진 고유의 항목으로 봐주시기 바랍니다.


8. marketing_start_at
- 공란은 어떤 의미인지 궁금합니다.
- marketing_start_at의 마케팅은 어떤 마케팅을 의미하는 건가요?
==> 판매가 시작된 날짜를 의미합니다. 공란은 무시하셔도 됩니다.


9. transaction_amount와 sale_price가 다른 이유(캡쳐 참고)
- 쿠폰 사용도 없는데 두 값이 차이가 발생
- 환불데이터는 차액 환불인건 지
- 환불이 아닌 데이터도 해당 현상발생
==> sale_price는 실제 판매가격, transaction_amount은 결제된 금액을 의미하며, 보유 포인트에 따라 차액발생 가능합니다.


10. GA 데이터는 어떤 데이터가 제공될 예정인지 궁금합니다.
==> 실습자 전용 계정 발행해드릴 예정입니다. 프로젝트 기간 동안 전체 데이터를 볼 수 있는 권한 드릴 예정입니다.

id : Dtype : int 추정(이하 추정 추가하지 않음) / 어떤 id인지 확인 필요 / 중복 여부 확인 / unique한 건가요?
=> 네. TransactionID 같은 느낌입니다. (각 거래내역에 대한 ID)

customer_id : Dtype: int / 어떤 고객 id 인지, 중복 있음. / 1대다수적인지
=> 중복이 있습니다. 왜냐면 같은 고객이 여러 강의를 결제할 수 있습니다. (물론 그거말고 취소 내역까지 포함하면 더 많은 경우)

course_id : Dtype: int / 빈 곳이 있던데 이유가? / 강의의 자체적 id번호 인 건지 다른 건지
=> 강의 자체의 id이고, 비어있는 값은 추가 확인이 필요할 것 같습니다. (저의 추측으로는 데이터를 추출할 당시에 폐기된 강의가 아닐까..)

type : Dtype: vchar OR string / order와 payment 기준 -> 고객이 낸 건지 다른 건지
=> order는 결제 페이지까지는 갔지만, 아직 결제하지 않은 상태(흔히 얘기하는 장바구니에 담음)이고, payment는 최종 결제가 일어난 상태입니다.

state : Dtype: varchar OR string / CANCELLED : 결제가 취소된 상황, PENDING : pg사에서 결제 완료가 안된 상태, DELETED : 테이블에서 제거를 해야하는 상태 -> COMPLETE : pg 처리까지 완료된 상태 맞나요?
=> 네 맞습니다.

course_title : Dtype: varchar OR string / 패키지와 아닌 것, 프로모션인 것 과 아닌 것 한정판매 및 프리패스, 평생소장 등의 기준을 잡고 분석하는 게 좋을까요?
=> 말씀하신것처럼 강의 기획별로 해도 좋고, 분야별(e.g. UX/UI, 프론트앤드 등..)로 분석하는것도 방법입니다.

category_title : Dtype: varchar OR string / 카테고리적 분류인 건지?
=> 네 맞습니다. 대분류 느낌입니다.

format : Dtype: varchar OR string / 올인원, 스쿨 온라인, 온라인 완주반, RED 등 나누는 기준도 따로 있을까요?
=> 이거는 강의 기획 당시에 어떤 형태로 만들었냐의 차이입니다. 올인원은 지금의 초격차 패키지랑 같은 컨셉이고, 온라인 완주반, The RED도 다른 형태의 기획 강의입니다.

completed_at : Dtype: date / 완료로 치는 기준, 강사분의 마지막 업로드 기준인지?
=> 결제 완료 시점입니다. 지금 이 데이터는 강의에 관련된 내용은 전혀 없고, 거래 내역 데이터입니다.

transaction_amount : Dtype: int / 총 금액인 건지, 총 금액 중 할인 등이 없는 가장 처음 책정된 금액인지
=> transaction이 거래 내역이라는 의미입니다. 최종 결제 금액입니다.

coupon_title : Dtype: varchar OR string / 단발성 쿠폰인지 아닌지 여부 및 한 강의만 적용되는 건지 여러번 되는 건지
=> 보통 coupon을 발행할 때는 강의별로 만드는건 아니고, 쿠폰의 효과가 적용된 다른 entity입니다. 여러 강의에 적용될 수 있습니다. 하지만 실제 coupon_id는 다르겠죠.

coupon_discount_amount : Dtype: int / 강의 한 편당 할인 금액인지 전체 할인 금액인지
=> 해당 row가 어떤 단위로 정의되었는지 고민해보시면 아실 수 있을 겁니다. (그리고 퍼센트 할인이라고 하면, 전체에 하든 개별로 하든 같습니다)

sale_price : Dtype: 마찬가지, 전체적 할인 금액인지, 쿠폰을 써야만 활성화 되는 등의 조건적 활성화 금액인건지
=> 쿠폰 말고도 이벤트 같은 다른 조건에 의한 할인도 있습니다. (데이터에 나와있음)

tax_free_amount : Dtype: int / transaction 기준인 건지 할인 및 추가적 적용 이후 금액인지
=> 원래는 VAT를 제외한 금액이어야 하는데, 주어진 데이터에서는 다 같습니다.

pg : Dtype: pg 가 무슨 단어의 약자인지 부터 기준 궁금합니다. 비어있는데 꼭 필요한 컬럼인지, 무슨 데이터 타입인건지..
=> PG(Payment Gateway)라고 해서 실제로 온라인 거래할 때 사용하는 금융거래 대행사를 의미합니다. (e.g. 카카오페이, 토스페이먼트, U+ pay 등..) 비어있는 것은 default PG사를 의미합니다. (LG U+ 같은 언급이 안되어있는 다른 회사중에 하나)

method : Dtype: varchar OR string / VBANK : 가상계좌 CARD의 의미 및 기준. 신용카드/체크카드 등. 구분 필요한지. -> 가상계좌라는 것이 계좌이체 및 네이버페이 등 이런 류를 모두 포함하는 건가요?
=> 아닙니다. 가상계좌를 통한 결제 방법을 의미합니다. 일반적인 다른 온라인 결제에서 통용되는 것과 같습니다.

subcategory_title : Dtype: varchar OR string / 서브 카테고리라고 되어있는데 category_title의 하위적 분류인 건지 별도인건지 체크 필요.
=> 하위 분류가 맞습니다.

marketing_start_at : Dtype: date / 마케팅 기준, 쿠폰인 건지 패키지인건지 등 기준 필요. 해당의 종료일도 필요한지.
=> 해당 강의의 마케팅이 시작된 기준입니다. 여기서 마케팅은 해당 강의를 판매한 시점이라고 생각하시면 됩니다. (즉, landing page가 최초로 올라간 시점)


Q1. pg라고 적힌 부분보면 이니시스나 카카오 뭐 이런게 있는데 null값으로 되어있는 부분이 있어서 이거는 어떤 식으로 결제 된건지 궁금합니다.
A1. PG가 null로 되어있는 부분은 default로 세팅된 다른 PG사라고 생각해주시면 됩니다.


Q2. marketing_start_at에 비어있는 값은 무엇인가요?
A2. marketing_start_at은 해당 강의가 판매를 시작한 시점입니다. 비어있는 값은 무시하셔도 좋습니다.


Q3. type에서 TRANSACTION은 무슨 뜻인가요?
A3. B2B CONTRACT로 생성된 데이터로 무시하셔도 됩니다.


Q4. state 컬럼에서 DELETED, PENDING, REQUESTED는 무슨 뜻인가요?
A4. REQUESTED는 고객에게 결제 요청을 보낸 상태입니다. 나머지는 무시하셔도 좋습니다.


Q5. method에 TRANS와 TRANSACTION이 있는데, 같은 건가요?
A5. 네 같은 데이터입니다. 역시나 무시하셔도 좋습니다.


Q6. type과 state를 연결해서 해석 부탁드립니다.
A6. type에서는 PAYMENT와 REFUND만 확인하시면 되고, state에서는 COMPLETED와 REQUESTED만 보시면 됩니다.


Q7. format 컬럼에서 모르는 내용들이 많은데, 정확히 어떤걸 의미하는지 설명해주세요.
A7. 공유드린 엑셀 파일에 "column별 설명" 시트에 자세히 적혀있습니다.


Q8. completed_at은 각 state에 대해서 클릭이 완료된 시각일까요? 판매를 시작했다는게 강의가 온라인으로 올라왔다는건지 결제가 된걸 판매 시작했다는건지 모르겠어요.
A8. completed_at의 정확한 정의는 state가 COMPLETED로 변경된 시각입니다. 현재 state에는 REQUESTED와 COMPLETED 뿐이기 때문에, REQUESTED였던 거래내역이 COMPLETED로 바뀔 때, 즉 실제 구매가 발생했을 때의 시각입니다.


Q9. coupon_discount_amount가 sale_price보다 크고 transaction_amount가 0보다 큰 데이터가 4개 존재합니다. 쿠폰 금액이 강의 가격보다 더 비싼데 결제를 한 이 데이터들은 어떻게 해석해야할지 여쭤보고 싶습니다.
A9. 이 데이터는 무시하셔도 좋습니다. (보안상 이슈로 자세한 답변이 어려움)


Q10. course_id가 비어있는 곳이 있던데 이유가 무엇인가요?
A10. course_id는 온라인, 오프라인 강의 등 강의의 자체적인 ID로 부여됩니다. 프로모션의 경우에는 따로 ID를 부여하지 않습니다.


Q11. type이 ORDER면 주문신청만 한 상태라 state는 COMPLETED가 없을 것 같은데 많이 존재해서 무슨 의미인지 모르겠습니다. 주문 신청한 상태에서도 결제가 완료될 수 있나요?
A11. ORDER 상태는 2021년 7월까지만 사용하던 상태로, 내부적으로 정의되어 사용되던 것이라 현재는 무시하셔도 좋습니다.


Q12. transaction_amount가 실제로 고객이 결제한 가격이고, sale_price가 강의 가격인것 같은데 coupon이 없는데 transaction_amount와 sale_price가 다른 데이터는 어떤 의미인가요?
A12. sale_price는 거래가 발생할 당시 해당 강의의 판매 가격이고, transaction_amount는 실제로 결제된 금액을 의미합니다. 네이버페이 등의 PG사에서 포인트 차감 등으로 차이가 발생할 수 있습니다.


Q13. type REQUESTED는 고객한테 결제 요청을 보낸 상태라고 이해하면 되나요?
A13. 네 정확합니다.


Q14. marketing_start_at의 의미가 헷갈리네요.. sns에 홍보가 시작된 시점인가요? 비어있는 데이터는 홍보를 안한거라고 생각하면 되는지 다른 의미가 있는지 궁금합니다.
A14. marketing_start_at은 해당 강의를 판매하기 시작한 날짜입니다. 웹 페이지 상에 landing page로 올라온 것을 기준으로 보시면 됩니다.


Q15. 해당 데이터가 기간에 발생한 모든 거래내역인가요? 아니면 샘플링된 데이터인가요? 만약에 전체 데이터라면 type이 바뀌게 되면 특정 row의 type이 update되나요?
A15. 제공되는 데이터는 해당 기간에 발생한 모든 데이터중에 개인정보 이슈가 있는 데이터들만 제외한 데이터입니다. type이 바뀌게 되면 새롭게 row가 추가됩니다.

# Data Skimming

In [49]:
import pandas as pd

df = pd.read_excel('EDAPJT_VER2_210329_210926.xlsx')
df

,id,customer_id,course_id,type,state,course_title,category_title,format,completed_at,transaction_amount,coupon_title,coupon_discount_amount,sale_price,tax_free_amount,pg,method,subcategory_title,marketing_start_at
0,970634,504760.0,201435.0,ORDER,CANCELLED,올인원 패키지 : 알고리즘 기술면접 완전 정복,프로그래밍,올인원,2021-03-28 15:00:11,90500,NaN,NaN,110500.0,110500.0,NaN,VBANK,개발자 커리어,NaT
1,970650,432862.0,203178.0,ORDER,CANCELLED,초격차 패키지 : 한번에 끝내는 영상 촬영과 편집,영상/3D,올인원,2021-03-28 15:16:53,96000,NaN,NaN,116000.0,116000.0,NaN,CARD,영상 편집,2020-12-02
2,970657,72297.0,204246.0,PAYMENT,COMPLETED,시크릿코드 : 프론트엔드 실무 완성편,프로그래밍,스쿨 온라인,2021-03-28 15:21:43,171810,[10% 할인] 시크릿코드 실무 완성편,19090.0,190900.0,190900.0,NaN,CARD,NaN,2021-03-04
3,970656,72297.0,204246.0,ORDER,CANCELLED,시크릿코드 : 프론트엔드 실무 완성편,프로그래밍,스쿨 온라인,2021-03-28 15:21:43,171810,NaN,NaN,190900.0,190900.0,NaN,CARD,NaN,2021-03-04
4,970658,478028.0,201797.0,PAYMENT,COMPLETED,올인원 패키지 : 직장인 필수 스킬 3종 세트 MAX,업무 생산성,올인원,2021-03-28 15:21:54,97500,[웰컴쿠폰] 올인원 패키지 2만원 할인 쿠폰,20000.0,117500.0,117500.0,NaN,CARD,PPT/보고서,2019-11-14
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
105414,1364995,640697.0,205365.0,PAYMENT,CANCELLED,초격차 패키지 : 한 번에 끝내는 유튜브 크리에이터 되기,영상/3D,올인원,2021-09-25 14:10:42,96000,[WELCOME] 온라인 강의 2만원 할인쿠폰,20000.0,116000.0,116000.0,INICIS,TRANS,영상 편집,2021-06-15
105415,1364998,670896.0,204159.0,PAYMENT,CANCELLED,부동산 디벨로퍼 아카데미 : 인허가,부동산/금융,올인원,2021-09-25 14:16:33,189000,NaN,NaN,189000.0,189000.0,INICIS,CARD,부동산 개발,2021-02-10
105416,1364996,640697.0,205365.0,PAYMENT,COMPLETED,초격차 패키지 : 한 번에 끝내는 유튜브 크리에이터 되기,영상/3D,올인원,2021-09-25 14:17:41,96000,[WELCOME] 온라인 강의 2만원 할인쿠폰,20000.0,116000.0,116000.0,INICIS,VBANK,영상 편집,2021-06-15
105417,1365005,670896.0,204159.0,PAYMENT,CANCELLED,부동산 디벨로퍼 아카데미 : 인허가,부동산/금융,올인원,2021-09-25 14:19:56,189000,NaN,NaN,189000.0,189000.0,INICIS,CARD,부동산 개발,2021-02-10
105418,1365007,610626.0,206720.0,PAYMENT,COMPLETED,용호수의 돈 버는 실전 영상 제작,영상/3D,올인원,2021-09-25 14:25:47,139000,[WELCOME] 온라인 강의 3만원 할인쿠폰,30000.0,169000.0,169000.0,NAVER,POINT,영상 편집,2021-08-17

In [50]:
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
plt.style.use('fivethirtyeight')
import warnings
warnings.filterwarnings('ignore')

In [51]:
info = pd.read_excel('EDAPJT_VER2_210329_210926.xlsx', sheet_name='column별 설명', header=None)
info

                         0                                                  1
0                       id                                해당 거래내역에 대한 ID (PK)
1              customer_id                                          결제한 고객 ID
2                course_id                 강의 ID, 프로모션에 대해서는 값이 할당되어 있지 않습니다.
3                     type                                             거래의 종류
4                    state                                          거래에 대한 상태
5             course_title                                              강의 제목
6           category_title                                                대분류
7                   format                                      온라인 강의의 기획 종류
8             completed_at                           state가 COMPLETED로 변경된 시점
9       transaction_amount                                           최종 결제 금액
10            coupon_title                                              쿠폰 종류
11  coupon_discount_amount                                           쿠폰 할인 금액
12              sale_price                                              판매 금액
13         tax_free_amount                                         보안상 공유가 힘듬
14                      pg                                             PG사 종류
15                  method                                              결제 방식
16       subcategory_title                                                중분류
17      marketing_start_at                          강의 판매 시점 (자세한 사항은 공유가 힘듬)
18                     NaN                                                NaN
19                     NaN                                                NaN
20                     NaN                                                NaN
21                     NaN                                                NaN
22                   type                                                  유형
23                   ORDER                                         DEPRECATED
24                 PAYMENT                                                 결제
25             TRANSACTION                                  B2B계약결제 (무시해도 좋음)
26                  REFUND                                                 환불
27                     NaN                                                NaN
28                   state                                                 상태
29               COMPLETED                                              결제 완료
30               REQUESTED                                         고객에게 결제 요청
31                 PENDING                                         보안 이슈로 공개X
32               CANCELLED                                         보안 이슈로 공개X
33                  HIDDEN                                         보안 이슈로 공개X
34                  DELETE                                         보안 이슈로 공개X
35                     NaN                                                NaN
36                     NaN                                                NaN
37                  format                                                NaN
38                     B2B                      B2B 온라인 외 기업강의 (기업교육 계약 시 생성)
39                 B2B 온라인  B2B 온라인 구독제 : 패키지 플랜, 올 플랜 등 패스트캠퍼스 온라인 강의를 구독...
40                     B2G  K-Digital Training, K-Digital Credit 등 정부 사업 (...
41                     MBA                                       MBA (경영학 석사)
42                     RED                                           연사 강조 강의
43                      관리                                                관리용
44                      스쿨                 커리어 교육 사업 : 오프라인 강의 (Snowball CIC)
45                  스쿨 온라인                  커리어 교육 사업 : 온라인 강의 (Snowball CIC)
46                    아카이브                                               아카이브
47                     온라인                                                  -
48                 온라인 완주반                          온라인 완주 즉, '완강' 시 환급해주는 상품
49                     올인원                          올인원 패키지, 초격차 패키지 등 온라인 강의
50                     이벤트                                                이벤트
51                      캠프          캠프 (오프라인 강의 : 주 2~3회 저녁 or 주말 시간 대 강의 진행)
52                     콜로소                        취미 교육 사업 : 온라인 강의 (콜로소 CIC)
53                  하루10분컷                                           Snowball

In [52]:
table = info.reset_index(drop=True).iloc[:18, :2]
table.loc[18] = ['completed - marketing_start', '강의판매 시점부터 결제완료시점까지의 기간']
table.columns = ['컬럼명', '설명']
dtype = pd.Series(['int', 'int', 'int', 'str', 'str', 'str','str',
                   'str', 'datetime', 'float', 'str','float', 'float',
                   'float', 'str', 'str', 'str', 'datetime', 'datetime'],
                  name='데이터타입')
table = pd.concat([table, dtype], axis=1)
print(table.to_markdown())

|    | 컬럼명                      | 설명                                                      | 데이터타입   |
|---:|:----------------------------|:----------------------------------------------------------|:-------------|
|  0 | id                          | 해당 거래내역에 대한 ID (PK)                              | int          |
|  1 | customer_id                 | 결제한 고객 ID                                            | int          |
|  2 | course_id                   | 강의 ID, 프로모션에 대해서는 값이 할당되어 있지 않습니다. | int          |
|  3 | type                        | 거래의 종류                                               | str          |
|  4 | state                       | 거래에 대한 상태                                          | str          |
|  5 | course_title                | 강의 제목                                                 | str          |
|  6 | category_title              | 대분류                                                    | str          |
|  7 | format                      | 온라인 강의의 기획 종류                                   | str          |
|  8 | completed_at                | state가 COMPLETED로 변경된 시점                           | datetime     |
|  9 | transaction_amount          | 최종 결제 금액                                            | float        |
| 10 | coupon_title                | 쿠폰 종류                                                 | str          |
| 11 | coupon_discount_amount      | 쿠폰 할인 금액                                            | float        |
| 12 | sale_price                  | 판매 금액                                                 | float        |
| 13 | tax_free_amount             | 보안상 공유가 힘듬                                        | float        |
| 14 | pg                          | PG사 종류                                                 | str          |
| 15 | method                      | 결제 방식                                                 | str          |
| 16 | subcategory_title           | 중분류                                                    | str          |
| 17 | marketing_start_at          | 강의 판매 시점 (자세한 사항은 공유가 힘듬)                | datetime     |
| 18 | completed - marketing_start | 강의판매 시점부터 결제완료시점까지의 기간                 | datetime     |

## Data Specification

|    | 컬럼명                      | 설명                                                      | 데이터타입   |
|---:|:----------------------------|:----------------------------------------------------------|:-------------|
|  0 | id                          | 해당 거래내역에 대한 ID (PK)                              | int          |
|  1 | customer_id                 | 결제한 고객 ID                                            | int          |
|  ~~2~~ | ~~course_id~~           | ~~강의 ID, 프로모션에 대해서는 값이 할당되어 있지 않습니다.~~| ~~int~~       |
|  3 | type                        | 거래의 종류                                               | str          |
|  4 | state                       | 거래에 대한 상태                                          | str          |
|  5 | course_title                | 강의 제목                                                 | str          |
|  6 | category_title              | 대분류                                                    | str          |
|  7 | format                      | 온라인 강의의 기획 종류                                   | str          |
|  8 | completed_at                | state가 COMPLETED로 변경된 시점                           | datetime     |
|  9 | transaction_amount          | 최종 결제 금액                                            | float        |
| 10 | coupon_title                | 쿠폰 종류                                                 | str          |
| 11 | coupon_discount_amount      | 쿠폰 할인 금액                                            | float        |
| 12 | sale_price                  | 판매 금액                                                 | float        |
| ~~13~~ | ~~tax_free_amount~~             | ~~보안상 공유가 힘듬~~                              | ~~float~~        |
| 14 | pg                          | PG사 종류                                                 | str          |
| 15 | method                      | 결제 방식                                                 | str          |
| 16 | subcategory_title           | 중분류                                                    | str          |
| 17 | marketing_start_at          | 강의 판매 시점 (자세한 사항은 공유가 힘듬)                | datetime     |
| 18 | completed - marketing_start | 강의판매 시점부터 결제완료시점까지의 기간                 | datetime     |

## Data Cleaning

### Drop columns
- course_id
- tax_free_amount

### Drop Data
- category_title
- course_title
- marketing_start_at : 별도의 데이터 프레임을 만든 후 제거(drop row가 너무 많음)

### Fill Data

- coupon_title : '없음'
- coupon_discount_amount : 0
- sale_price : transaction_amount
- pg : 'TOSS'
- method : 'CASH'
- subcategory_title : '없음'

In [53]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 105419 entries, 0 to 105418
Data columns (total 18 columns):
 #   Column                  Non-Null Count   Dtype
---  ------                  --------------   -----
 0   id                      105419 non-null  int64
 1   customer_id             105416 non-null  float64
 2   course_id               100212 non-null  float64
 3   type                    105419 non-null  object
 4   state                   105419 non-null  object
 5   course_title            105403 non-null  object
 6   category_title          105395 non-null  object
 7   format                  105403 non-null  object
 8   completed_at            105419 non-null  datetime64[ns]
 9   transaction_amount      105419 non-null  int64
 10  coupon_title            31817 non-null   object
 11  coupon_discount_amount  31817 non-null   float64
 12  sale_price              104291 non-null  float64
 13  tax_free_amount         104291 non-null  float64
 14  pg                      90344 non-null   object
 15  method                  92323 non-null   object
 16  subcategory_title       85590 non-null   object
 17  marketing_start_at      87440 non-null   datetime64[ns]
dtypes: datetime64[ns](2), float64(5), int64(2), object(9)
memory usage: 14.5+ MB

In [54]:
df.isnull().sum()

id                            0
customer_id                   3
course_id                  5207
type                          0
state                         0
course_title                 16
category_title               24
format                       16
completed_at                  0
transaction_amount            0
coupon_title              73602
coupon_discount_amount    73602
sale_price                 1128
tax_free_amount            1128
pg                        15075
method                    13096
subcategory_title         19829
marketing_start_at        17979
dtype: int64

In [55]:
df = df.drop(columns=['course_id', 'tax_free_amount'])
df

,id,customer_id,type,state,course_title,category_title,format,completed_at,transaction_amount,coupon_title,coupon_discount_amount,sale_price,pg,method,subcategory_title,marketing_start_at
0,970634,504760.0,ORDER,CANCELLED,올인원 패키지 : 알고리즘 기술면접 완전 정복,프로그래밍,올인원,2021-03-28 15:00:11,90500,NaN,NaN,110500.0,NaN,VBANK,개발자 커리어,NaT
1,970650,432862.0,ORDER,CANCELLED,초격차 패키지 : 한번에 끝내는 영상 촬영과 편집,영상/3D,올인원,2021-03-28 15:16:53,96000,NaN,NaN,116000.0,NaN,CARD,영상 편집,2020-12-02
2,970657,72297.0,PAYMENT,COMPLETED,시크릿코드 : 프론트엔드 실무 완성편,프로그래밍,스쿨 온라인,2021-03-28 15:21:43,171810,[10% 할인] 시크릿코드 실무 완성편,19090.0,190900.0,NaN,CARD,NaN,2021-03-04
3,970656,72297.0,ORDER,CANCELLED,시크릿코드 : 프론트엔드 실무 완성편,프로그래밍,스쿨 온라인,2021-03-28 15:21:43,171810,NaN,NaN,190900.0,NaN,CARD,NaN,2021-03-04
4,970658,478028.0,PAYMENT,COMPLETED,올인원 패키지 : 직장인 필수 스킬 3종 세트 MAX,업무 생산성,올인원,2021-03-28 15:21:54,97500,[웰컴쿠폰] 올인원 패키지 2만원 할인 쿠폰,20000.0,117500.0,NaN,CARD,PPT/보고서,2019-11-14
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
105414,1364995,640697.0,PAYMENT,CANCELLED,초격차 패키지 : 한 번에 끝내는 유튜브 크리에이터 되기,영상/3D,올인원,2021-09-25 14:10:42,96000,[WELCOME] 온라인 강의 2만원 할인쿠폰,20000.0,116000.0,INICIS,TRANS,영상 편집,2021-06-15
105415,1364998,670896.0,PAYMENT,CANCELLED,부동산 디벨로퍼 아카데미 : 인허가,부동산/금융,올인원,2021-09-25 14:16:33,189000,NaN,NaN,189000.0,INICIS,CARD,부동산 개발,2021-02-10
105416,1364996,640697.0,PAYMENT,COMPLETED,초격차 패키지 : 한 번에 끝내는 유튜브 크리에이터 되기,영상/3D,올인원,2021-09-25 14:17:41,96000,[WELCOME] 온라인 강의 2만원 할인쿠폰,20000.0,116000.0,INICIS,VBANK,영상 편집,2021-06-15
105417,1365005,670896.0,PAYMENT,CANCELLED,부동산 디벨로퍼 아카데미 : 인허가,부동산/금융,올인원,2021-09-25 14:19:56,189000,NaN,NaN,189000.0,INICIS,CARD,부동산 개발,2021-02-10
105418,1365007,610626.0,PAYMENT,COMPLETED,용호수의 돈 버는 실전 영상 제작,영상/3D,올인원,2021-09-25 14:25:47,139000,[WELCOME] 온라인 강의 3만원 할인쿠폰,30000.0,169000.0,NAVER,POINT,영상 편집,2021-08-17

In [56]:
df = df.dropna(subset=['category_title'])
df

,id,customer_id,type,state,course_title,category_title,format,completed_at,transaction_amount,coupon_title,coupon_discount_amount,sale_price,pg,method,subcategory_title,marketing_start_at
0,970634,504760.0,ORDER,CANCELLED,올인원 패키지 : 알고리즘 기술면접 완전 정복,프로그래밍,올인원,2021-03-28 15:00:11,90500,NaN,NaN,110500.0,NaN,VBANK,개발자 커리어,NaT
1,970650,432862.0,ORDER,CANCELLED,초격차 패키지 : 한번에 끝내는 영상 촬영과 편집,영상/3D,올인원,2021-03-28 15:16:53,96000,NaN,NaN,116000.0,NaN,CARD,영상 편집,2020-12-02
2,970657,72297.0,PAYMENT,COMPLETED,시크릿코드 : 프론트엔드 실무 완성편,프로그래밍,스쿨 온라인,2021-03-28 15:21:43,171810,[10% 할인] 시크릿코드 실무 완성편,19090.0,190900.0,NaN,CARD,NaN,2021-03-04
3,970656,72297.0,ORDER,CANCELLED,시크릿코드 : 프론트엔드 실무 완성편,프로그래밍,스쿨 온라인,2021-03-28 15:21:43,171810,NaN,NaN,190900.0,NaN,CARD,NaN,2021-03-04
4,970658,478028.0,PAYMENT,COMPLETED,올인원 패키지 : 직장인 필수 스킬 3종 세트 MAX,업무 생산성,올인원,2021-03-28 15:21:54,97500,[웰컴쿠폰] 올인원 패키지 2만원 할인 쿠폰,20000.0,117500.0,NaN,CARD,PPT/보고서,2019-11-14
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
105414,1364995,640697.0,PAYMENT,CANCELLED,초격차 패키지 : 한 번에 끝내는 유튜브 크리에이터 되기,영상/3D,올인원,2021-09-25 14:10:42,96000,[WELCOME] 온라인 강의 2만원 할인쿠폰,20000.0,116000.0,INICIS,TRANS,영상 편집,2021-06-15
105415,1364998,670896.0,PAYMENT,CANCELLED,부동산 디벨로퍼 아카데미 : 인허가,부동산/금융,올인원,2021-09-25 14:16:33,189000,NaN,NaN,189000.0,INICIS,CARD,부동산 개발,2021-02-10
105416,1364996,640697.0,PAYMENT,COMPLETED,초격차 패키지 : 한 번에 끝내는 유튜브 크리에이터 되기,영상/3D,올인원,2021-09-25 14:17:41,96000,[WELCOME] 온라인 강의 2만원 할인쿠폰,20000.0,116000.0,INICIS,VBANK,영상 편집,2021-06-15
105417,1365005,670896.0,PAYMENT,CANCELLED,부동산 디벨로퍼 아카데미 : 인허가,부동산/금융,올인원,2021-09-25 14:19:56,189000,NaN,NaN,189000.0,INICIS,CARD,부동산 개발,2021-02-10
105418,1365007,610626.0,PAYMENT,COMPLETED,용호수의 돈 버는 실전 영상 제작,영상/3D,올인원,2021-09-25 14:25:47,139000,[WELCOME] 온라인 강의 3만원 할인쿠폰,30000.0,169000.0,NAVER,POINT,영상 편집,2021-08-17

In [57]:
df.isnull().sum()

id                            0
customer_id                   0
type                          0
state                         0
course_title                  0
category_title                0
format                        0
completed_at                  0
transaction_amount            0
coupon_title              73578
coupon_discount_amount    73578
sale_price                 1112
pg                        15058
method                    13095
subcategory_title         19805
marketing_start_at        17955
dtype: int64

In [58]:
values = {'coupon_title': '없음', 'coupon_discount_amount': 0,
          'pg': 'TOSS', 'method': 'CASH', 'subcategory_title': '없음'}
df = df.fillna(value=values)

In [59]:
temp_idx = df[df.sale_price.isnull()].index

In [60]:
df[['sale_price', 'transaction_amount', 'coupon_discount_amount']]

        sale_price  transaction_amount  coupon_discount_amount
0         110500.0               90500                     0.0
1         116000.0               96000                     0.0
2         190900.0              171810                 19090.0
3         190900.0              171810                     0.0
4         117500.0               97500                 20000.0
...            ...                 ...                     ...
105414    116000.0               96000                 20000.0
105415    189000.0              189000                     0.0
105416    116000.0               96000                 20000.0
105417    189000.0              189000                     0.0
105418    169000.0              139000                 30000.0

[105395 rows x 3 columns]

In [61]:
df[df.sale_price.isnull() & (df.coupon_discount_amount != 0)]

Empty DataFrame
Columns: [id, customer_id, type, state, course_title, category_title, format, completed_at, transaction_amount, coupon_title, coupon_discount_amount, sale_price, pg, method, subcategory_title, marketing_start_at]
Index: []

In [62]:
df.loc[:, 'sale_price'] = df.loc[:, 'sale_price'].mask(df.sale_price.isnull(), df.transaction_amount)

In [63]:
df

,id,customer_id,type,state,course_title,category_title,format,completed_at,transaction_amount,coupon_title,coupon_discount_amount,sale_price,pg,method,subcategory_title,marketing_start_at
0,970634,504760.0,ORDER,CANCELLED,올인원 패키지 : 알고리즘 기술면접 완전 정복,프로그래밍,올인원,2021-03-28 15:00:11,90500,없음,0.0,110500.0,TOSS,VBANK,개발자 커리어,NaT
1,970650,432862.0,ORDER,CANCELLED,초격차 패키지 : 한번에 끝내는 영상 촬영과 편집,영상/3D,올인원,2021-03-28 15:16:53,96000,없음,0.0,116000.0,TOSS,CARD,영상 편집,2020-12-02
2,970657,72297.0,PAYMENT,COMPLETED,시크릿코드 : 프론트엔드 실무 완성편,프로그래밍,스쿨 온라인,2021-03-28 15:21:43,171810,[10% 할인] 시크릿코드 실무 완성편,19090.0,190900.0,TOSS,CARD,없음,2021-03-04
3,970656,72297.0,ORDER,CANCELLED,시크릿코드 : 프론트엔드 실무 완성편,프로그래밍,스쿨 온라인,2021-03-28 15:21:43,171810,없음,0.0,190900.0,TOSS,CARD,없음,2021-03-04
4,970658,478028.0,PAYMENT,COMPLETED,올인원 패키지 : 직장인 필수 스킬 3종 세트 MAX,업무 생산성,올인원,2021-03-28 15:21:54,97500,[웰컴쿠폰] 올인원 패키지 2만원 할인 쿠폰,20000.0,117500.0,TOSS,CARD,PPT/보고서,2019-11-14
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
105414,1364995,640697.0,PAYMENT,CANCELLED,초격차 패키지 : 한 번에 끝내는 유튜브 크리에이터 되기,영상/3D,올인원,2021-09-25 14:10:42,96000,[WELCOME] 온라인 강의 2만원 할인쿠폰,20000.0,116000.0,INICIS,TRANS,영상 편집,2021-06-15
105415,1364998,670896.0,PAYMENT,CANCELLED,부동산 디벨로퍼 아카데미 : 인허가,부동산/금융,올인원,2021-09-25 14:16:33,189000,없음,0.0,189000.0,INICIS,CARD,부동산 개발,2021-02-10
105416,1364996,640697.0,PAYMENT,COMPLETED,초격차 패키지 : 한 번에 끝내는 유튜브 크리에이터 되기,영상/3D,올인원,2021-09-25 14:17:41,96000,[WELCOME] 온라인 강의 2만원 할인쿠폰,20000.0,116000.0,INICIS,VBANK,영상 편집,2021-06-15
105417,1365005,670896.0,PAYMENT,CANCELLED,부동산 디벨로퍼 아카데미 : 인허가,부동산/금융,올인원,2021-09-25 14:19:56,189000,없음,0.0,189000.0,INICIS,CARD,부동산 개발,2021-02-10
105418,1365007,610626.0,PAYMENT,COMPLETED,용호수의 돈 버는 실전 영상 제작,영상/3D,올인원,2021-09-25 14:25:47,139000,[WELCOME] 온라인 강의 3만원 할인쿠폰,30000.0,169000.0,NAVER,POINT,영상 편집,2021-08-17

In [75]:
df.loc[df.category_title == '데이터 사이언스', 'category_title'] = '데이터사이언스'
df

,id,customer_id,type,state,course_title,category_title,format,completed_at,transaction_amount,coupon_title,coupon_discount_amount,sale_price,pg,method,subcategory_title,marketing_start_at
0,970634,504760.0,ORDER,CANCELLED,올인원 패키지 : 알고리즘 기술면접 완전 정복,프로그래밍,올인원,2021-03-28 15:00:11,90500,없음,0.0,110500.0,TOSS,VBANK,개발자 커리어,NaT
1,970650,432862.0,ORDER,CANCELLED,초격차 패키지 : 한번에 끝내는 영상 촬영과 편집,영상/3D,올인원,2021-03-28 15:16:53,96000,없음,0.0,116000.0,TOSS,CARD,영상 편집,2020-12-02
2,970657,72297.0,PAYMENT,COMPLETED,시크릿코드 : 프론트엔드 실무 완성편,프로그래밍,스쿨 온라인,2021-03-28 15:21:43,171810,[10% 할인] 시크릿코드 실무 완성편,19090.0,190900.0,TOSS,CARD,없음,2021-03-04
3,970656,72297.0,ORDER,CANCELLED,시크릿코드 : 프론트엔드 실무 완성편,프로그래밍,스쿨 온라인,2021-03-28 15:21:43,171810,없음,0.0,190900.0,TOSS,CARD,없음,2021-03-04
4,970658,478028.0,PAYMENT,COMPLETED,올인원 패키지 : 직장인 필수 스킬 3종 세트 MAX,업무 생산성,올인원,2021-03-28 15:21:54,97500,[웰컴쿠폰] 올인원 패키지 2만원 할인 쿠폰,20000.0,117500.0,TOSS,CARD,PPT/보고서,2019-11-14
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
105414,1364995,640697.0,PAYMENT,CANCELLED,초격차 패키지 : 한 번에 끝내는 유튜브 크리에이터 되기,영상/3D,올인원,2021-09-25 14:10:42,96000,[WELCOME] 온라인 강의 2만원 할인쿠폰,20000.0,116000.0,INICIS,TRANS,영상 편집,2021-06-15
105415,1364998,670896.0,PAYMENT,CANCELLED,부동산 디벨로퍼 아카데미 : 인허가,부동산/금융,올인원,2021-09-25 14:16:33,189000,없음,0.0,189000.0,INICIS,CARD,부동산 개발,2021-02-10
105416,1364996,640697.0,PAYMENT,COMPLETED,초격차 패키지 : 한 번에 끝내는 유튜브 크리에이터 되기,영상/3D,올인원,2021-09-25 14:17:41,96000,[WELCOME] 온라인 강의 2만원 할인쿠폰,20000.0,116000.0,INICIS,VBANK,영상 편집,2021-06-15
105417,1365005,670896.0,PAYMENT,CANCELLED,부동산 디벨로퍼 아카데미 : 인허가,부동산/금융,올인원,2021-09-25 14:19:56,189000,없음,0.0,189000.0,INICIS,CARD,부동산 개발,2021-02-10
105418,1365007,610626.0,PAYMENT,COMPLETED,용호수의 돈 버는 실전 영상 제작,영상/3D,올인원,2021-09-25 14:25:47,139000,[WELCOME] 온라인 강의 3만원 할인쿠폰,30000.0,169000.0,NAVER,POINT,영상 편집,2021-08-17

In [79]:
df.to_csv('Fastcampus_data_after_cleaning.csv')

In [78]:
df2 = df.dropna()
df2.to_csv('Fastcampus_data_after_cleaning_판매시작일결측치제거_Ver.csv', encoding='utf8')

In [71]:
df.customer_id.value_counts().to_frame()

          customer_id
98685.0            78
50769.0            62
40783.0            59
496508.0           54
427973.0           51
...               ...
551151.0            1
465616.0            1
281799.0            1
551081.0            1
610626.0            1

[53740 rows x 1 columns]

In [ ]:
df[df.customer_id.isnull()]

In [ ]:
df.drop([12133, 36367, 91500]).isnull().sum()

In [ ]:
df = df.drop([12133, 36367, 91500])

In [ ]:
df.reset_index()

In [ ]:
df = df.drop(columns='tax_free_amount')
df

In [ ]:
list(set(df.category_title.values))

In [ ]:
df[df.category_title.isnull()]

In [ ]:
mask = df.course_title.str.contains('B2B')
df[df.sale_price.isnull() & mask]

In [ ]:
df[df.course_id.isnull()].loc[:, 'course_title']

In [ ]:
df[df.course_title.isnull()]

## Categorical Features

### Course Category
- '투자/재테크'

- '마케팅'

- '프로그래밍'

- '영상/3D'

- '관리'

- '일러스트'

- '데이터사이언스'

- '부동산/금융'

- '비즈니스'

- '디자인'

- '지식콘텐츠'

- '업무 생산성'

- '교육'

- '데이터 사이언스'

- '파이낸스'

- '크리에이티브'

#### Cleaning overlapped data
-> 데이터사이언스가 두번 겹침

So, '데이터 사이언스'를 '데이터사이언스로 변경

In [ ]:
list(set(df[df.category_title == '데이터 사이언스'].index.values))

In [ ]:
df.loc[[47407, 47408, 47447, 47448, 47462, 47477, 47478, 47509, 94948], 'category_title'] = ['데이터사이언스' for i in range(9)]

In [ ]:
list(set(df.category_title.values))

### Amount of course for each category

- course_id가 null인 케이스 분석

In [ ]:
df.course_id.isnull()

In [ ]:
df[df.course_id.isnull()].loc[:, 'course_title']

In [ ]:
mask1 = df.course_id.isnull()
mask2 = df.loc[:, 'course_title'].str.contains('프로모션')
mask3 = df.loc[:, 'course_title'].str.contains('한정판매')
len(df[mask1 & mask2]) + len(df[mask1 & mask3])

In [ ]:
"""
course_id가 null인 케이스 분석
1. 프로모션
2. 한정판매
3. 그 외(NaN, 초격차 패키지, 올인원 패키지, 묶음)

-> 그 외 분석을 위해 차집합 join을 활용
"""
df[mask1].merge(
    df[mask1 & (mask2 | mask3)], on='id', how='left', indicator=True
).query(
    '_merge == "left_only"'
).drop(
    '_merge', 1
)['course_title_x']

In [ ]:
pd.pivot_table(
    data=df, columns='category_title', index='course_title'
).count().index

In [ ]:
pd.pivot_table(
    data=df, columns='category_title', index='course_title'
)['customer_id'].count()

In [ ]:
category_course_table = pd.pivot_table(
    data=df, columns='category_title', index='course_title'
)['course_id'].count()
category_course_table = category_course_table.rename('course_count')
category_course_table.sort_values(ascending=False, inplace=True)
category_course_table

In [ ]:
print(category_course_table.to_markdown())

| category_title   |   course_count |
|:-----------------|---------------:|
| 교육             |            879 |
| 프로그래밍       |            214 |
| 데이터사이언스   |            174 |
| 크리에이티브     |             89 |
| 마케팅           |             83 |
| 업무 생산성      |             73 |
| 부동산/금융      |             54 |
| 디자인           |             28 |
| 영상/3D          |             24 |
| 비즈니스         |              9 |
| 투자/재테크      |              8 |
| 파이낸스         |              3 |
| 관리             |              1 |
| 일러스트         |              1 |
| 지식콘텐츠       |              1 |

In [ ]:
# import matplotlib
# import matplotlib.font_manager as fm
# fm.get_fontconfig_fonts()
# font_location = 'C:/Users/piy81/AppData/Local/Microsoft/Windows/Fonts/NanumGothic.ttf' # For Windows
# font_name = fm.FontProperties(fname=font_location).get_name()
# matplotlib.rc('font', family=font_name)

import matplotlib_inline.backend_inline
matplotlib_inline.backend_inline.set_matplotlib_formats('retina')
plt.rc('font', family='AppleGothic')
plt.rc('axes', unicode_minus=False)

| category_title   |   course_count |
|:-----------------|---------------:|
| 프로그래밍       |            195 |
| 데이터사이언스   |            140 |
| 크리에이티브     |             76 |
| 마케팅           |             73 |
| 업무 생산성      |             68 |
| 부동산/금융      |             49 |
| 교육             |             39 |
| 디자인           |             28 |
| 영상/3D          |             24 |
| 비즈니스         |              8 |
| 투자/재테크      |              8 |
| 파이낸스         |              2 |
| 관리             |              1 |
| 일러스트         |              1 |
| 지식콘텐츠       |              1 |

In [ ]:
_, ax = plt.subplots(2, 1, figsize=(16,20))
ax[0].pie(category_course_table.values, labels=category_course_table.index,
          autopct='%1.1f%%', shadow=True)
ax[0].set_title('Course amount for each category')
sns.barplot(x=category_course_table.index, y=category_course_table.values, ax=ax[1])
ax[1].set_title('Course amount for each category')
plt.show()

#### Observations:

### Sale price for each category

In [ ]:
pd.pivot_table(data=df[df.type == 'PAYMENT'], columns='category_title', index='course_title')['transaction_amount'].sum()

In [ ]:
pd.pivot_table(data=df[df.type == 'REFUND'], columns='category_title', index='course_title')['transaction_amount'].sum()

In [ ]:
pd.pivot_table(data=df[df.type == 'ORDER'], columns='category_title', index='course_title')['transaction_amount'].sum()

In [ ]:
transaction_category = pd.pivot_table(data=df[(df.type == 'PAYMENT') | (df.type == 'REFUND')], 
                                columns='category_title',index='course_title')['transaction_amount'].sum()
transaction_category.rename('transaction amount for each category', inplace=True)
transaction_category.sort_values(ascending=False, inplace=True)
transaction_category

In [ ]:
df.describe()

In [ ]:
sales_category = pd.pivot_table(data=df[(df.type == 'PAYMENT') | (df.type == 'REFUND')], 
                                columns='category_title',index='course_title')['sale_price'].sum()
sales_category.rename('sales for each category', inplace=True)
sales_category.sort_values(ascending=False, inplace=True)
sales_category

In [ ]:
pd.concat([transaction_category, sales_category], axis=1)

In [ ]:
_, ax = plt.subplots(2, 1, figsize=(16,20))
ax[0].pie(sales_category.values, labels=sales_category.index,
          autopct='%1.1f%%', shadow=True)
ax[0].set_title('Sales for each category')
sns.barplot(x=sales_category.index, y=sales_category.values, ax=ax[1])
ax[1].set_title('Sales for each category')
plt.show()

In [ ]:
list(set(df[df.category_title == '교육'].course_title.values))

### Observations:

- 카테고리별 매출을 비교해보면, **'교육'** 카테고리가 매출의 **54.2%**를 차지하고 있다.<br><br>

  - '교육' 카테고리에 어떤 강의들이 있는지 확인해보면, 모든 강의이름 앞에 (B2B)라는 접두어가 붙은 것으로 보아 **B2B교육** 분야임을 확인할 수 있다.<br>

  - 즉, 패스트캠퍼스의 주 수입원이 기업임을 확인할 수 있다.<br><br>

- 나머지 45.8%가 B2C인 것을 감안하면, B2C 카테고리도 굉장히 중요한 부분이다.<br><br>

  - B2C 카테고리에서 가장 많은 매출을 차지하는 부분을 확인해보면, 놀랍게도 **'데이터사이언스'** 카테고리였다.<br>

  - 이것이 단순히 수요가 많아서 매출이 높은 것인지 패캠에서 강의를 많이 열어서 그런 것인지 인과관계를 확인할 수는 없지만, 일단 가장 주력 카테고리임은 확실히 알 수 있다.<br>
  
  - **프로그래밍** 카테고리는 강의개수가 가장 많은 것에 비해 매출이 **B2C 중 4등**이라는 점이 주목할만한 점이다.

In [ ]:
customer = pd.pivot_table(data=df, index='customer_id')
customer

In [ ]:
print(list(set(df.type.values)))

In [ ]:
print(list(set(df.state.values)))

In [76]:
print(list(set(df.category_title.values)))
df[df.category_title == '데이터 사이언스']

['관리', '데이터사이언스', '투자/재테크', '프로그래밍', '교육', '일러스트', '업무 생산성', '지식콘텐츠', '파이낸스', '비즈니스', '크리에이티브', '디자인', '영상/3D', '마케팅', '부동산/금융']

Empty DataFrame
Columns: [id, customer_id, type, state, course_title, category_title, format, completed_at, transaction_amount, coupon_title, coupon_discount_amount, sale_price, pg, method, subcategory_title, marketing_start_at]
Index: []

In [ ]:
print(list(set(df.format.values)))

In [ ]:
print(list(set(df.pg.values)))

In [ ]:
print(list(set(df.method.values)))

In [ ]:
df[df.method.isnull()]

In [ ]:
print(list(set(df.subcategory_title.values)))

In [ ]:
print(list(set(df.coupon_title.values)))

In [ ]:
print(list(set(df[df.category_title == '마케팅'].subcategory_title.values)))

In [ ]:
df[df.marketing_start_at.isnull()]